2022-01-17 19:13:42,806 INFO    MainThread:3256 [wandb_setup.py:_flush():71] setting env: {}
2022-01-17 19:13:42,807 INFO    MainThread:3256 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-17 19:13:42,807 INFO    MainThread:3256 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-01-17 19:13:42,807 INFO    MainThread:3256 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-17 19:13:42,807 INFO    MainThread:3256 [wandb_init.py:_log_setup():371] Logging user logs to /Users/charlesoneill/Documents/GitHub/charlieoneill/_notebooks/wandb/run-20220117_191342-3cs8wgwc/logs/debug.log
2022-01-17 19:13:42,807 INFO    MainThread:3256 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/charlesoneill/Documents/GitHub/charlieoneill/_notebooks/wandb/run-20220117_191342-3cs8wgwc/logs/debug-internal.log
2022-01-17 19:13:42,807 INFO    MainThread:3256 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9c931dffd0>
2022-01-17 19:13:42,808 INFO    MainThread:3256 [wandb_init.py:init():404] calling init triggers
2022-01-17 19:13:42,808 INFO    MainThread:3256 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-17 19:13:42,808 INFO    MainThread:3256 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 11k47lkc
2022-01-17 19:13:42,809 INFO    MainThread:3256 [wandb_run.py:finish():1457] finishing run charlieoneill/basic-intro/11k47lkc
2022-01-17 19:13:42,810 INFO    MainThread:3256 [jupyter.py:save_history():429] not saving jupyter history
2022-01-17 19:13:42,810 INFO    MainThread:3256 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-17 19:13:42,810 INFO    MainThread:3256 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-17 19:13:42,812 INFO    MainThread:3256 [wandb_init.py:init():460] starting backend
2022-01-17 19:13:42,812 INFO    MainThread:3256 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-01-17 19:13:42,816 INFO    MainThread:3256 [backend.py:ensure_launched():216] starting backend process...
2022-01-17 19:13:42,828 INFO    MainThread:3256 [backend.py:ensure_launched():221] started backend process with pid: 3385
2022-01-17 19:13:42,831 INFO    MainThread:3256 [wandb_init.py:init():469] backend started and connected
2022-01-17 19:13:42,849 INFO    MainThread:3256 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-17 19:13:42,850 INFO    MainThread:3256 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-01-17 19:13:42,850 INFO    MainThread:3256 [wandb_init.py:init():533] updated telemetry
2022-01-17 19:13:42,886 INFO    MainThread:3256 [wandb_init.py:init():563] communicating current version
2022-01-17 19:13:43,770 INFO    MainThread:3256 [wandb_init.py:init():568] got version response 
2022-01-17 19:13:43,770 INFO    MainThread:3256 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-17 19:13:44,143 INFO    MainThread:3256 [wandb_init.py:init():606] starting run threads in backend
2022-01-17 19:13:49,222 INFO    MainThread:3256 [wandb_run.py:_console_start():1810] atexit reg
2022-01-17 19:13:49,225 INFO    MainThread:3256 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-17 19:13:49,225 INFO    MainThread:3256 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-17 19:13:49,230 INFO    MainThread:3256 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-17 19:13:49,231 INFO    MainThread:3256 [wandb_init.py:init():633] run started, returning control to user process
2022-01-17 20:30:30,223 INFO    MainThread:3256 [wandb_setup.py:_flush():71] setting env: {}
2022-01-17 20:30:30,224 INFO    MainThread:3256 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-17 20:30:30,224 INFO    MainThread:3256 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-01-17 20:30:30,224 INFO    MainThread:3256 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-17 20:30:30,224 INFO    MainThread:3256 [wandb_init.py:_log_setup():371] Logging user logs to /Users/charlesoneill/Documents/GitHub/charlieoneill/_notebooks/wandb/run-20220117_203030-3fe6rlli/logs/debug.log
2022-01-17 20:30:30,224 INFO    MainThread:3256 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/charlesoneill/Documents/GitHub/charlieoneill/_notebooks/wandb/run-20220117_203030-3fe6rlli/logs/debug-internal.log
2022-01-17 20:30:30,224 INFO    MainThread:3256 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9c9314d8b0>
2022-01-17 20:30:30,225 INFO    MainThread:3256 [wandb_init.py:init():404] calling init triggers
2022-01-17 20:30:30,225 INFO    MainThread:3256 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-17 20:30:30,225 INFO    MainThread:3256 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 3cs8wgwc
2022-01-17 20:30:30,227 INFO    MainThread:3256 [wandb_run.py:finish():1457] finishing run charlieoneill/my-test-project/3cs8wgwc
2022-01-17 20:30:30,228 INFO    MainThread:3256 [jupyter.py:save_history():429] not saving jupyter history
2022-01-17 20:30:30,228 INFO    MainThread:3256 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-17 20:30:30,228 INFO    MainThread:3256 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-17 20:30:30,229 INFO    MainThread:3256 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-17 20:30:30,233 INFO    MainThread:3256 [wandb_run.py:_restore():1752] restore
2022-01-17 20:30:30,675 INFO    MainThread:3256 [wandb_run.py:_restore():1752] restore
2022-01-17 20:30:30,702 ERROR   MainThread:3256 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1963, in _on_finish
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 67, in _publish_telemetry
    self._publish(rec)
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 45, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 437, in init
    self._wl._global_run_stack[-1].finish()
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1463, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1797, in _atexit_cleanup
    self._backend.cleanup()
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
