
    status_response = self._interface.communicate_network_status()
Error in callback <function _WandbInit._pause_backend at 0x7f9c93191040> (for post_run_cell):
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 125, in communicate_network_status
    resp = self._communicate(req, local=True)
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    resp = self._communicate_network_status(status)
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 388, in _communicate_network_status
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")    resp = self._communicate(req, local=True)
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
Exception: The wandb backend process has shutdown
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/charlesoneill/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Error in callback <function _WandbInit._resume_backend at 0x7f9c92b02e50> (for pre_run_cell):